app_id: "APP ID HERE"
app_secret: "APP SECRET HERE"
redirect: "REDIRECT URL HERE"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/TENANT ID HERE"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"