# Generated by Django 3.0.3 on 2020-02-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('role', models.CharField(choices=[('Voter', 'Voter'), ('Candidate', 'Candidate'), ('Election Commission', 'Election Commission')], default='Voter', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
